### ISSUE TITLE
Dicomviewer App not working after installing App Files Right Click

### ISSUE THREAD

**Issue by nagodoy** [ayselafsar/dicomviewer#53] opened 2019-01-20 03:47 UTC
Steps to reproduce
Install App Dicomviewer
Install App. Files Right Click
Open Dicom Folder
Crash on the DICOM screen, not working
Series and Images not viewed
Opening only one dcm image is OK

Server configuration
Operating system:
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic

Web server:
Apache 2

Data base:
PostgreSQL

PHP version:
7.2

Nextcloud version: (see Nextcloud admin page)
15.0.2

App DicomVIewer v 1.1.0

App Files Right Click 0.10.1

Nextcloud.log without error message

![captura de tela 2019-01-20 as 01 22 32](https://user-images.githubusercontent.com/3387863/51435013-0ef13f00-1c55-11e9-85e6-77d415c1d1db.png)

Thanks,
Nelson

**Comment by ayselafsar** [comment] 2019-05-19 13:36
Closing since I could not reproduce this issue and did not get any console log for further investigation. Please feel free to reopen this issue with your console logs if you still have it with the latest version.

**Closed by ayselafsar** 2019-05-19 13:36 UTC
Labels: bug
