### ISSUE TITLE
Dicom viewer error

### ISSUE THREAD

**Issue by Harrykuch** [ayselafsar/dicomviewer#106] opened 2024-03-25 10:22 UTC
Hi.
I open the dicom file on my server. The error appears in a new window:

Internal Server Error
The request could not be processed by the server.
If this happens again, send the server administrator a detailed message about what happened below.
Detailed information can be found in the server log.

Client details: Desktop Win 11 64b Chrome 123.0.6312.58
Server details: Linux raspberrypi 6.6.20+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64
Nextcloud Hub 7 (28.0.3)

Nextcloud log:
ValueError Path cannot be empty
foreach() argument must be of type array|object, string given at /var/www/html/nextcloud/apps/dicomviewer/templates/viewer.php#12
foreach() argument must be of type array\|object, string given at /var/www/html/nextcloud/apps/dicomviewer/lib/Controller/DisplayController.php#51

![2024-03-25_13-07-50](https://github.com/ayselafsar/dicomviewer/assets/164869034/75c4851e-7c20-4090-8bc3-0400dfd5ac2e)
![image](https://github.com/ayselafsar/dicomviewer/assets/164869034/b455d04f-3cd4-4366-ae98-95c85044d361)
![image](https://github.com/ayselafsar/dicomviewer/assets/164869034/abfa14f2-c182-4fef-b308-20928bfa0ed9)

What to do?

**Comment by ayselafsar** [comment] 2024-03-26 15:26
Duplicate of #103 
Fixed by #105

**Comment by Argon267** [comment] 2024-03-27 19:39
Getting still the same error after update:

ValueError - Path cannot be empty
foreach() argument must be of type array|object, string given at /var/www/nextcloud/apps/dicomviewer/templates/viewer.php#12

**Comment by Harrykuch** [comment] 2024-03-27 19:57
> Getting still the same error after update:
> 
> ValueError - Path cannot be empty foreach() argument must be of type array|object, string given at /var/www/nextcloud/apps/dicomviewer/templates/viewer.php#12

Yes!

**Comment by ayselafsar** [comment] 2024-03-27 21:53
Confirmed that we have missed to fix it in that file, will apply a fix soon.

**Closed** 2024-03-27 22:35 UTC
Labels: bug, verified

**Comment by Harrykuch** [comment] 2024-03-28 07:50
I tested the application. The viewer is working. Thank you! 👍
