### ISSUE TITLE
Love it! Can I connect an entire folder into a series?

### ISSUE THREAD

**Issue by nickisashkir** [ayselafsar/dicomviewer#43] opened 2019-01-12 08:28 UTC
Hello! My name is Nick, and I started using DICOM Viewer. It was the entire reason I decided to use Nextcloud. I need a heart transplant, and trying to keep my medical data sorted is a tough task. I'm tired of every time I go to a new doctor, I have to fill out entire request forms, etc for the data. I have many disks, thousands of pages of paper, and many DICOM files. 

My DICOM files are sorted by date, procedure, and Series. So I have a Echocardiogram with 4 series (Series1, Series2, Series3, Series4) for example. I uploaded them to my Nextcloud to a folder like HealthData/<date> echocardiogram/Series1/ and have 100 DCMs to that series in there.

How can I connect my entire subfolder to be all 1 series, so it's easy to scroll/list through them? 

Edit: I can open an entire folder as a series, which does what I want. Can I suggest a forward/back when you are inside of a folder to automatically connect the series and not have to preload it? Trying to load large studies with a giant folder and several video dcm files takes a a while.

**Comment by doc-sebastian** [comment] 2019-01-12 11:09
The sorting is based on the dicom series tag included in the images and not 
related to the nextcloud plugin. You can use a freeware tools to modify the 
dicom tags prior to uploading them to nextcloud, e.g. by a tool called 
dicomviewer


Am 12. Januar 2019 09:28:42 schrieb nickisashkir <notifications@github.com>:

**Comment by nickisashkir** [comment] 2019-01-12 16:33
Thank you. I'll find out how to edit the tags. The CD's given to us has the software automatically refer to the next image in the structure and at the end it states "No more images".

**Comment by nickisashkir** [comment] 2019-01-12 16:50
Hello. I just downloaded a handful of DICOM tools. They all connect the series as 1 automatically and I can easily navigate back/forth. 

In these tools a few of my files are videos. But, the DICOM Viewer in NextCloud doesn't play the video as well.

**Comment by nickisashkir** [comment] 2019-01-12 17:02
Opening the entire folder into the Dicom Viewer worked. I was under the assumption that clicking one could connect the next image in the series. I would like to suggest that as a feature.

**Comment by ayselafsar** [comment] 2019-01-13 02:33
Closed as duplicate of #44 and #24

**Closed by ayselafsar** 2019-01-13 02:33 UTC
Labels: duplicate
