### ISSUE TITLE
Nextcloud 18 compatibility

### ISSUE THREAD

**Issue by tuxmaster5000** [ayselafsar/dicomviewer#68] opened 2020-03-10 08:25 UTC
The current version are marked not compatibility with NC 18.

**Comment by ayselafsar** [comment] 2020-03-10 08:55
@tuxmaster5000 Thanks for the report. It will be fixed ASAP.

**Comment by ciroiriarte** [comment] 2020-03-30 03:46
+1 to this :)

Thanks a lot for the app, really useful!

**Comment by hooger** [comment] 2020-04-07 10:28
I see that it is marked as uncompatible, but what does it actually mean? Is it currently unusable, makes NC unstable, or is it just not tested according to some standards?
Thanks in advance!

**Comment by Lars1963** [comment] 2020-04-07 12:28
You can safely use it with NC latest release (18.03). I'm using it since 18 beta 1 without any problems.
Also on 19 beta 1 I encountered no problems until now.
@ayselafsar  Maybe time for a updared release?

**Comment by ayselafsar** [comment] 2020-04-07 14:30
v1.2.2 was released with Nextcloud 18 compatibility.

Please note that DICOM Viewer Sidebar are not shown in Nextcloud 18 due to the latest changes in Nextcloud.

Leaving this issue open to enable DICOM Viewer Sidebar in Nextcloud 18

**Comment by RainerEmrich** [comment] 2020-07-30 08:17
> v1.2.2 was released with Nextcloud 18 compatibility.
> 
> Please note that DICOM Viewer Sidebar are not shown in Nextcloud 18 due to the latest changes in Nextcloud.
> 
> Leaving this issue open to enable DICOM Viewer Sidebar in Nextcloud 18
@ayselafsar We probably should aim for Nextcloud 19 compatibility. So, changing subject?

**Comment by crami** [comment] 2020-08-25 14:09
Nextcloud 19 is out, and the current version seams not to work.

**Comment by MetabAli** [comment] 2020-08-25 23:41
when sharing a dicom folder containing dicom files without dcm extension, the shared links only allows download without a way to view them.
in other word, is it possible when sharing dicom folder it will load the dicom viewer automatically ?
![image](https://user-images.githubusercontent.com/45373499/91238383-92361900-e745-11ea-988d-ce45253b804f.png)

**Comment by ayselafsar** [comment] 2021-11-28 15:47
Closed as duplicate of #76

**Closed by ayselafsar** 2021-11-28 15:47 UTC
Labels: duplicate, enhancement
