### ISSUE TITLE
DCM Picture not showing up

### ISSUE THREAD

**Issue by hast0011** [ayselafsar/dicomviewer#6] opened 2018-02-28 21:28 UTC
Menu line of the program appears then it displays "Loading... 100%" forever. Happens with different files from different "supplier".

**Comment by ayselafsar** [comment] 2018-02-28 21:32
Is there any error in web console? That might also be related to DICOM file. Is there any chance to send me the anonymized version of DICOM file?

**Comment by hast0011** [comment] 2018-02-28 21:48
Hello, I don't know how to anonymize the picture. It looks like binary :-). Can I have a look into some logfile or run a command in order to get more messages?

**Comment by hast0011** [comment] 2018-02-28 21:50
Do you have a DICOM file "anonymized" to show that installation works?

**Comment by ayselafsar** [comment] 2018-02-28 21:56
You can give it a try with this file:
[sample.zip](https://github.com/ayselafsar/dicomviewer/files/1768998/sample.zip)

Please send me web console logs.

**Comment by hast0011** [comment] 2018-02-28 22:00
Same thing with that one. What do you mean by web console logs, where to find? Sorry

**Comment by ayselafsar** [comment] 2018-02-28 22:04
On Chrome: Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac)

**Comment by hast0011** [comment] 2018-02-28 22:08
I didn't know this exists, however in MS-Egde now: Cant copy text inthis box, therefore the screenshot only.

![unbenannt](https://user-images.githubusercontent.com/33160182/36815826-352252f0-1cdc-11e8-9990-944de4ad7a60.PNG)

**Comment by hast0011** [comment] 2018-02-28 22:14
root@debian:/var/www/nextcloud/apps/dicomviewer/img# ls -la
insgesamt 36
drwxr-xr-x 2 www-data www-data 4096 Feb 20 18:43 .
drwxr-xr-x 8 www-data www-data 4096 Feb 20 18:43 ..
-rw-r--r-- 1 www-data www-data  699 Feb 20 18:43 ._app-dark.svg
-rw-r--r-- 1 www-data www-data  931 Feb 20 18:43 app-dark.svg
-rw-r--r-- 1 www-data www-data  975 Feb 20 18:43 app.svg
-rw-r--r-- 1 www-data www-data  120 Feb 20 18:43 ._.DS_Store
-rw-r--r-- 1 www-data www-data 6148 Feb 20 18:43 .DS_Store
-rw-r--r-- 1 www-data www-data  590 Feb 20 18:43 rotate-right.svg
root@debian:/var/www/nextcloud/apps/dicomviewer/img#

The file "app-dark.svg" seems to be there.

**Comment by hast0011** [comment] 2018-02-28 22:15
I have to leave for today. Early start tomorrow morning. Thank you for your help.

**Comment by ayselafsar** [comment] 2018-02-28 22:15
Are you using the "snap" version of Nextcloud (which was installed using its snap package)?

**Comment by hast0011** [comment] 2018-02-28 22:17
I was using a procedure like this: https://linuxconfig.org/how-to-install-nextcloud-on-debian-9-stretch-linux

**Comment by SkyBehind** [comment] 2018-03-21 01:29
I want to chime in here with the same issue. I'm stuck at 100% loading as well.  I can give you a non-anonymized dicom file if that would help.  I also tried with the sample file.

**Comment by ayselafsar** [comment] 2018-03-21 01:36
Hi @SkyBehind 
Thanks for the report. It would be great if you can send me anonymized DICOM file to reproduce it with. Also, do you use Debian as well?

**Comment by SkyBehind** [comment] 2018-03-21 01:38
Server is Ubuntu Server 16.04, Nextcloud is installed in a Docker, with a separate container for a MariaDB database.  It's behind a reverse proxy that serves it up with SSL from letsencrypt.

I'm viewing it on a Mac, using Chrome.  I don't know how to strip it, so I was just going to send you a non-anon file.  How can I send?

**Comment by ayselafsar** [comment] 2018-03-21 01:48
Unfortunately, I cannot accept non-anonymized DICOM files. You can use [DICOM Cleaner](http://www.dclunie.com/pixelmed/software/webstart/DicomCleanerUsage.html) or any other software to anonymize (please make sure that you anonymize all PHI attributes and blackout PHI if embedded on image). In the meantime, i will check it with the Nextcloud docker image.

**Comment by wjwieland** [comment] 2018-04-01 21:02
Hoping I can help identify this issue:
Am running Nextcloud 13.01 on Ubuntu 14.04.
The console (Chrome Dev Tools) reports the following:
`GET https://my.server.org/apps/dicomviewer/img/app-dark.svg 404 (Not Found)
`
`Failed to decode downloaded font: https://my.server.org/nextcloud/apps/dicomviewer/css/external/font-awesome/fonts/fontawesome-webfont.woff2
`
`OTS parsing error: Failed to convert WOFF 2.0 font to SFNT`

`GET ttps://my.server.org/apps/dicomviewer/js/public/cornerstoneWADOImageLoaderWebWorker.js 404 (Not Found)`

Note that the first and last of the two entries above do not have a correct path called out:  The path is:
`https://my.server.org/apps/.....`
When it should be:
`https://my.server.org/nextcloud/apps/.....`

If you need I can send (I think, have never tried. Using GinkoCadx 3.7.1) you an anonymized file.  Just let me know.  That said, I think the problem is that the correct path is not being picked up by some parts of the JS code in the application.  

Hope that is helpful with this issue.  I spend a fair amount of time with various Dr.s, some of whom do not have ready access to my med records. (Multiple Myeloma)  As such, when I have questions for them it is very useful to be able to simply log into my nextcloud and show them what I am asking about.  It is very encouraging to me to see an app like this!  

Again, I hope this is helpful.  Please do let me know if I can provide any further info...

**Comment by ayselafsar** [comment] 2018-04-02 03:21
Hi @wjwieland ,
Thank you for the detailed report. I applied a fix to support for nextcloud instances running in subfolder (like in your description). 
Could you please give it a try with v0.0.4 and let me know?
Thanks.

**Comment by wjwieland** [comment] 2018-04-04 22:41
@ayselafsar 
The upgrade to V0.5 showed up in my nextcloud apps, so I let it rock-and-roll.  The images showed up immediately!  I will have to play with the rest of the functionality now, but am very pleased with the apparent speed of rendering thus far!  Thank you so very much for this improvement.  I am of the opinion that this bug should be closed out at this point, though I will defer to the person who originally opened the issue.  Thanks again!

**Comment by ayselafsar** [comment] 2018-04-04 22:50
Great, i am closing this issue then. Please reopen if you will see it again.

**Closed by ayselafsar** 2018-04-04 22:50 UTC
Labels: bug
